"""
Hướng dẫn sử dụng Flamegraph Profiling trên Windows
"""

print("="*70)
print("🔥 FLAMEGRAPH PROFILING FOR WINDOWS")
print("="*70)

print("\nPyFlame (https://github.com/CTO92/PyFlame) là một deep learning")
print("framework, KHÔNG PHẢI là profiling tool!")
print("\nĐể có flamegraph profiling trên Windows, dùng các tool sau:\n")

print("="*70)
print("OPTION 1: py-spy (KHUYẾN NGHỊ - Dễ nhất, tốt nhất!)")
print("="*70)
print("\n📦 Cài đặt:")
print("   pip install py-spy")
print("\n🔥 Sử dụng:")
print("   # Profile script và tạo flamegraph")
print("   py-spy record -o flamegraph.svg -- python your_script.py")
print("   ")
print("   # Profile script đang chạy (lấy PID)")
print("   py-spy record -o flamegraph.svg --pid 12345")
print("   ")
print("   # Live view (real-time)")
print("   py-spy top -- python your_script.py")
print("\n✅ Ưu điểm:")
print("   - Không cần sửa code")
print("   - Overhead thấp (~1%)")
print("   - Tạo SVG flamegraph đẹp")
print("   - Cross-platform (Windows/Linux/Mac)")

print("\n" + "="*70)
print("OPTION 2: flameprof (Dùng với cProfile)")
print("="*70)
print("\n📦 Cài đặt:")
print("   pip install flameprof")
print("\n🔥 Sử dụng:")
print("   # Profile script")
print("   python -m cProfile -o profile.stats your_script.py")
print("   ")
print("   # Tạo flamegraph")
print("   flameprof profile.stats > flamegraph.svg")
print("   ")
print("   # Hoặc dùng profiling_cpu.py của chúng ta:")
print("   from profiling_cpu import CPUProfiler")
print("   profiler = CPUProfiler()")
print("   profiler.start()")
print("   # your code")
print("   profiler.stop()  # Tự động tạo flamegraph.svg")
print("\n✅ Ưu điểm:")
print("   - Dùng cProfile có sẵn")
print("   - Chi tiết hơn")
print("   - Tích hợp vào code dễ dàng")

print("\n" + "="*70)
print("OPTION 3: snakeviz (Interactive visualization)")
print("="*70)
print("\n📦 Cài đặt:")
print("   pip install snakeviz")
print("\n🔥 Sử dụng:")
print("   # Profile script")
print("   python -m cProfile -o profile.stats your_script.py")
print("   ")
print("   # Visualize (mở browser)")
print("   snakeviz profile.stats")
print("\n✅ Ưu điểm:")
print("   - Interactive web UI")
print("   - Dễ explore")
print("   - Sunburst/Icicle charts")

print("\n" + "="*70)
print("OPTION 4: PyInstrument (Simple & Clean)")
print("="*70)
print("\n📦 Cài đặt:")
print("   pip install pyinstrument")
print("\n🔥 Sử dụng:")
print("   # Command line")
print("   pyinstrument your_script.py")
print("   ")
print("   # In code")
print("   from pyinstrument import Profiler")
print("   profiler = Profiler()")
print("   profiler.start()")
print("   # your code")
print("   profiler.stop()")
print("   profiler.print()")
print("\n✅ Ưu điểm:")
print("   - Output đẹp, dễ đọc")
print("   - HTML report")
print("   - Sampling profiler (low overhead)")

print("\n" + "="*70)
print("🎯 RECOMMENDATION CHO DỰ ÁN CỦA BẠN")
print("="*70)
print("\n1. Cho development/debugging:")
print("   👉 Dùng CPUProfiler trong profiling_cpu.py")
print("   👉 Cài thêm: pip install flameprof")
print("   👉 Sẽ tự động tạo flamegraph.svg")

print("\n2. Cho production/monitoring:")
print("   👉 Dùng py-spy")
print("   👉 pip install py-spy")
print("   👉 Chạy: py-spy record -o profile.svg -- python api_server.py")

print("\n3. Cho quick analysis:")
print("   👉 Dùng PyInstrument")
print("   👉 pip install pyinstrument")
print("   👉 Chạy: pyinstrument train_wav2vec2.py")

print("\n" + "="*70)
print("📝 DEMO: Profile training script")
print("="*70)
print("\n# Cách 1: Sử dụng py-spy (không cần sửa code)")
print("py-spy record -o train_profile.svg -- python train_wav2vec2.py")

print("\n# Cách 2: Sử dụng profiling_cpu.py")
print("# Thêm vào đầu train_wav2vec2.py:")
print("from profiling_cpu import CPUProfiler")
print("profiler = CPUProfiler()")
print("profiler.start()")
print("# ... existing code ...")
print("profiler.stop()  # Tạo flamegraph tự động")

print("\n# Cách 3: PyInstrument (simplest)")
print("pyinstrument train_wav2vec2.py")

print("\n" + "="*70)
print("✅ Kết luận:")
print("="*70)
print("\nPyFlame (GitHub CTO92) KHÔNG PHẢI là profiling tool!")
print("Nó là deep learning framework cho Cerebras WSE hardware.")
print("\nĐể profile Python trên Windows, dùng:")
print("  1. py-spy (best for flamegraph)")
print("  2. flameprof (works with cProfile)")
print("  3. PyInstrument (simple & clean)")
print("  4. profiling_cpu.py (custom tool đã có sẵn)")
print("\n" + "="*70)

# Offer to install
print("\n📦 Muốn cài ngay?")
print("   pip install py-spy pyinstrument flameprof snakeviz")
print("="*70)
